# Meta Data for SEO

## Homepage
title = "Jitsuin RKVST"
titleSeparator = "-"
titleAddition = "Multi-Party Trust Automation"
description = "Jitsuin RKVST is a Multi-Party Trust Platform powered by the Blockchain"

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = ""
twitterCreator = ""
facebookAuthor = ""
facebookPublisher = ""
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/jitsuin-inc"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 90
bgColor = "#fff"
landscapePhotoWidths = [2000, 1500, 1000, 500]
portraitPhotoWidths = [2000, 1500, 1000]
lqipWidth = "10x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a> and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://www.github.com/jitsuin-inc/archivist-docs"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
